# Taken from https://www.llm-prices.com/
# Moving to here until PRs are review e.g. https://github.com/simonw/llm-prices/pull/48
PRICES = {
    "updated_at": "2026-02-22",
    "prices": [
        {
            "id": "amazon-nova-micro",
            "vendor": "amazon",
            "name": "Amazon Nova Micro",
            "input": 0.035,
            "output": 0.14,
            "input_cached": None,
        },
        {
            "id": "amazon-nova-premier",
            "vendor": "amazon",
            "name": "Amazon Nova Premier",
            "input": 2.5,
            "output": 12.5,
            "input_cached": None,
        },
        {
            "id": "amazon-nova-2-omni-preview",
            "vendor": "amazon",
            "name": "Amazon Nova 2 Omni (Preview)",
            "input": 0.3,
            "output": 2.5,
            "input_cached": None,
        },
        {
            "id": "amazon-nova-2-pro-preview",
            "vendor": "amazon",
            "name": "Amazon Nova 2 Pro (Preview)",
            "input": 1.25,
            "output": 10.0,
            "input_cached": None,
        },
        {
            "id": "amazon-nova-2-lite",
            "vendor": "amazon",
            "name": "Amazon Nova 2 Lite",
            "input": 0.3,
            "output": 2.5,
            "input_cached": None,
        },
        {
            "id": "amazon.titan-image-generator-v2:0",
            "vendor": "amazon",
            "name": "Titan Image Generator v2*",
            "input": 5.0,
            "output": 5.0,
            "input_cached": None,
        },
        {
            "id": "amazon.nova-canvas-v1:0",
            "vendor": "amazon",
            "name": "Amazon Nova Canvas v1*",
            "input": 20.0,
            "output": 20.0,
            "input_cached": None,
        },
        {
            "id": "claude-4.5-haiku",
            "vendor": "anthropic",
            "name": "Claude 4.5 Haiku",
            "input": 1,
            "output": 5,
            "input_cached": None,
        },
        {
            "id": "claude-sonnet-5",
            "vendor": "anthropic",
            "name": "Claude Sonnet 5",
            "input": 3,
            "output": 15,
            "input_cached": None,
        },
        {
            "id": "claude-opus-4.8",
            "vendor": "anthropic",
            "name": "Claude Opus 4.8",
            "input": 5,
            "output": 25,
            "input_cached": None,
        },
        {
            "id": "claude-fable-5",
            "vendor": "anthropic",
            "name": "Claude Fable 5",
            "input": 10.0,
            "output": 50.0,
            "input_cached": None,
        },
        {
            "id": "gemini-3.1-pro-preview",
            "vendor": "google",
            "name": "Gemini 3.1 Pro",
            "input": 2,
            "output": 12,
            "input_cached": None,
        },
        {
            "id": "gemini-3.5-flash",
            "vendor": "google",
            "name": "Gemini 3.5 Flash",
            "input": 1.5,
            "output": 9,
            "input_cached": 0.15,
        },
        {
            "id": "gemini-3.1-flash-lite",
            "vendor": "google",
            "name": "Gemini 3.1 Flash-Lite",
            "input": 0.25,
            "output": 1.5,
            "input_cached": 0.025,
        },
        {
            "id": "gemini-3.1-flash-tts-preview",
            "vendor": "google",
            "name": "Gemini 3.1 Flash TTS Preview",
            "input": 1,
            "output": 20,
            "input_cached": None,
        },
        {
            "id": "gpt-5.5",
            "vendor": "openai",
            "name": "GPT-5.5",
            "input": 5.0,
            "output": 30.0,
            "input_cached": 0.5,
        },
        {
            "id": "gpt-5.4",
            "vendor": "openai",
            "name": "GPT-5.4",
            "input": 2.5,
            "output": 15.0,
            "input_cached": 0.25,
        },
        {
            "id": "gpt-5.4-mini",
            "vendor": "openai",
            "name": "GPT-5.4 Mini",
            "input": 0.75,
            "output": 4.5,
            "input_cached": 0.075,
        },
        {
            "id": "gpt-image-1",
            "vendor": "openai",
            "name": "gpt-image-1 (image gen)",
            "input": 10,
            "output": 40,
            "input_cached": 1.25,
        },
        {
            "id": "gpt-image-1-mini",
            "vendor": "openai",
            "name": "gpt-image-1-mini (image gen)",
            "input": 2,
            "output": 8,
            "input_cached": 0.2,
        },
        {
            "id": "gpt-image-1.5",
            "vendor": "openai",
            "name": "gpt-image-1.5 (image gen)",
            "input": 5,
            "output": 34,
            "input_cached": None,
        },
        {
            "id": "gemini-3-pro-image",
            "vendor": "google",
            "name": "Gemini 3 Pro Image Preview",
            "input": 2.0,
            "output": 134.0,
            "input_cached": None,
        },
        {
            "id": "gemini-3.1-flash-image",
            "vendor": "google",
            "name": "Gemini 3.1 Flash Image Preview*",
            "input": 0.5,
            "output": 67.2,
            "input_cached": None,
        },
        {
            "id": "gemini-3.1-flash-lite-image",
            "vendor": "google",
            "name": "Gemini 3.1 Flash-Lite Image Preview*",
            "input": 0.25,
            "output": 33.6,
            "input_cached": None,
        },
        {
            "id": "imagen-4",
            "vendor": "google",
            "name": "Imagen 4*",
            "input": 20.0,
            "output": 20.0,
            "input_cached": None,
        },
        {
            "id": "imagen-4-fast",
            "vendor": "google",
            "name": "Imagen 4 Fast*",
            "input": 10.0,
            "output": 10.0,
            "input_cached": None,
        },
        {
            "id": "imagen-4-ultra",
            "vendor": "google",
            "name": "Imagen 4 Ultra*",
            "input": 30.0,
            "output": 30.0,
            "input_cached": None,
        },
        {
            "id": "imagen-4.0-ultra-generate-001",
            "vendor": "google",
            "name": "Imagen 4.0 Ultra Generate 001*",
            "input": 30.0,
            "output": 30.0,
            "input_cached": None,
        },
        {
            "id": "imagen-4.0-fast-generate-001",
            "vendor": "google",
            "name": "Imagen 4.0 Fast Generate 001*",
            "input": 10.0,
            "output": 10.0,
            "input_cached": None,
        },
        {
            "id": "chirp_3",
            "vendor": "google",
            "name": "GCP Chirp 3 (STT)*",
            # $0.016 per minute ~ $0.96 per hour.
            # 1M tokens ≈ 5000 minutes => $80.00
            # Splitting cost 50/50 between input and output tokens for comparison.
            "input": 40.0,
            "output": 40.0,
            "input_cached": None,
        },
        {
            "id": "aws-polly",
            "vendor": "amazon",
            "name": "AWS Polly*",
            # $16.00 per 1 million characters.
            # 1M tokens ≈ 4M characters => $64.00
            # Splitting cost 50/50 between input and output tokens for comparison.
            "input": 32.0,
            "output": 32.0,
            "input_cached": None,
        },
        {
            "id": "aws-transcribe",
            "vendor": "amazon",
            "name": "AWS Transcribe*",
            # $0.024 per minute => $1.44 per hour.
            # 1M tokens ≈ 5000 minutes => $120.00
            # Splitting cost 50/50 between input and output tokens for comparison.
            "input": 60.0,
            "output": 60.0,
            "input_cached": None,
        },
        {
            "id": "gcp-chirp3-tts",
            "vendor": "google",
            "name": "GCP Chirp 3 (TTS)*",
            # $16.00 per 1 million characters.
            # 1M tokens ≈ 4M characters => $64.00
            # Splitting cost 50/50 between input and output tokens for comparison.
            "input": 32.0,
            "output": 32.0,
            "input_cached": None,
        },
        {
            "id": "aws-translate",
            "vendor": "amazon",
            "name": "AWS Translate*",
            # $15.00 per 1 million characters (standard translation).
            # 1M tokens ≈ 4M characters => $60.00
            # Splitting cost 50/50 between input and output tokens for comparison.
            "input": 30.0,
            "output": 30.0,
            "input_cached": None,
        },
        {
            "id": "gemma-4-26b-a4b-it",
            "vendor": "google",
            "name": "Gemma 4 26B (open source)",
            "input": 0,
            "output": 0,
            "input_cached": None,
        },
        {
            "id": "gemma-4-31b-it",
            "vendor": "google",
            "name": "Gemma 4 31B (open source)",
            "input": 0,
            "output": 0,
            "input_cached": None,
        },
        {
            "id": "gcp-translate",
            "vendor": "google",
            "name": "GCP Cloud Translation*",
            # $20.00 per 1 million characters (Basic/Advanced NMT).
            # 1M tokens ≈ 4M characters => $80.00
            # Splitting cost 50/50 between input and output tokens for comparison.
            "input": 40.0,
            "output": 40.0,
            "input_cached": None,
        },
    ],
    "aliases": {
        "claude-opus": "claude-opus-4.8",
        "claude-opus-latest": "claude-opus-4.8",
        "claude-haiku-4-5": "claude-4.5-haiku",
        "nova-2-lite": "amazon-nova-2-lite",
        "nova-micro": "amazon-nova-micro",
        "nova-premier": "amazon-nova-premier",
        "gcp-chirp3": "chirp_3",
        "aws-translate": "aws-translate",
        "gcp-translate": "gcp-translate",
        "anthropic-5-fable": "claude-fable-5",
        "anthrophic-5-fable": "claude-fable-5",
        "nano-banana-2-lite": "gemini-3.1-flash-lite-image",
    },
}
